package:
  name: opencv3
  version: 3.0.0

source:
  fn: opencv-3.0.0.tar.gz
  url: https://github.com/Itseez/opencv/archive/3.0.0.tar.gz
  sha256: da51a4e459b0bcbe14fb847c4f168415f421765fb91996f42b9e1ce0575f05d5
  
  patches:
    - cap_mpjpeg_decoder.patch  # [win]
    - detection_based_filter.patch  # [win and py27]
    - no_rpath.patch

requirements:
  build:
   - python
   - cmake
   - numpy
   - eigen 3.2.7
   - tbb 4.3_20141023  # [osx]
   - msinttypes r26  # [win and py<35]

  run:
   - python
   - numpy
   - tbb 4.3_20141023  # [osx]

test:
  imports:
    - cv2
    - cv2.xfeatures2d

about:
  home: http://opencv.org/
  license: BSD
